name: CI/CD for ASP.NET Core and Azure Static Web Apps

on:
  push:
    branches:
      - main
      - hotfix
  pull_request:
    branches:
      - main
      - hotfix

permissions:
  contents: read

jobs:
  build_dotnet:
    runs-on: ubuntu-latest
    name: Build and Deploy ASP.NET Core App
    if: github.event_name == 'push' || github.event_name == 'pull_request'
    steps:
      - name: Print Hello World
        run: echo "Hello, world from build dotnet!"

  deploy_dotnet:
    runs-on: ubuntu-latest
    needs: build_dotnet

    steps:
      - name: Print Hello World
        run: echo "Hello, world from deploy dotnet!"

  send_email:
    runs-on: ubuntu-latest
    needs: [deploy_dotnet, deploy_dotnet]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "14"

      - name: Install dependencies
        run: npm install @sendgrid/mail

      - name: Send email on Failure
        if: ${{ failure() }}
        run: |
          node ./.github/sendgrid.js
        env:
          SENDGRID_API_KEY: ${{ secrets.SENDGRID_API_KEY }}
          EVENT_NAME: ${{ github.event_name }}
          REPOSITORY: ${{ github.repository }}
          REF: ${{ github.ref }}
          SUCCESS: false

      - name: Send email on success
        if: ${{ success() }}
        run: |
          node ./.github/sendgrid.js
        env:
          SENDGRID_API_KEY: ${{ secrets.SENDGRID_API_KEY }}
          EVENT_NAME: ${{ github.event_name }}
          REPOSITORY: ${{ github.repository }}
          REF: ${{ github.ref }}
          SUCCESS: true
