name: CI/CD for ASP.NET Core and Azure Static Web Apps

on:
  push:
    branches:
      - main
      - hotfix
  pull_request:
    branches:
      - main
      - hotfix

permissions:
  contents: read

jobs:
  build_dotnet:
    runs-on: ubuntu-latest
    name: Build and Deploy ASP.NET Core App
    if: github.event_name == 'push' || github.event_name == 'pull_request'
    steps:
      - name: Print Hello World
        run: echo "Hello, world from build dotnet!"

  deploy_dotnet:
    runs-on: ubuntu-latest
    needs: build_dotnet

    steps:
      - name: Print Hello World
        run: echo "Hello, world from deploy dotnet!"

  send_email:
    runs-on: ubuntu-latest
    needs: [deploy_dotnet, deploy_dotnet]
    steps:
      - name: Send email on Failure
        if: ${{ failure() }}
        uses: cquintini/sendgrid-action@v1.0.1
        env:
          SENDGRID_API_KEY: ${{ secrets.SENDGRID_API_KEY }}
          EVENT: ${{ github.event_name }}
          REPOSITORY: ${{ github.repository }}
          REF: ${{ github.ref }}
          SUCCESS: false

      - name: Send email on success
        if: ${{ success() }}
        uses: cquintini/sendgrid-action@v1.0.1
        env:
          SENDGRID_API_KEY: ${{ secrets.SENDGRID_API_KEY }}
          EVENT: ${{ github.event_name }}
          REPOSITORY: ${{ github.repository }}
          REF: ${{ github.ref }}
          SUCCESS: true
